version: "3"
services:
  tcpprobe:
    image: mehrdadrad/tcpprobe
    hostname: tcpprobe
    ports:
      - "8081:8081"
    entrypoint:
      ["tcpprobe", "-i", "20s", "https://www.google.com", "https://github.com"]

  prometheus:
    image: prom/prometheus:latest
    hostname: prom
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - ./:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
