apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tcpprobe
  labels:
    app: tcpprobe
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tcpprobe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tcpprobe
subjects:
  - kind: ServiceAccount
    name: tcpprobe
    namespace: {{ .Values.namespace}}
